server:
  port: 7777
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #gateway ?????????????????????????????????? router??? router ?????????????????????
          lower-case-service-id: true  #????????????????
      routes:

        - id: product-service                # ??id???????????
          uri: http://localhost:8888         # ???????
          predicates:
            - Path=/product/**               # ?????Path????????/product/???????

        - id: order-service
          uri: http://localhost:9999
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/hhhh              # ????, ??order-demo??????server.servlet.context-path=/hhhh

